#+TITLE: Emacs Configuration
#+PROPERTY: header-args :results silent :tangle yes

* How this works

- This file is picked up by [[https://github.com/nix-community/emacs-overlay][emacs overlay]] and scanned for ~use-package-forms~.
- The required packages are installed.
- The tangled blocks are byte-compiled and written to ~/nix/store/...-emacs-default-0.1.0~,
  which is then loaded magically by emacs.

* TODO code evaluation in orgmode
** c++
** c#
* TODO early-init.el
* Other configs

https://github.com/winny-/emacs.d

** M-EMACS

https://github.com/MatthewZMD/.emacs.d

* Preamble
#+begin_src emacs-lisp
;;; ...  -*- lexical-binding: t -*-
#+end_src

* Package setup

Packages are handled by nix, but it's still useful to imperatively
install stuff for testing.

** package

#+begin_src emacs-lisp
   (require 'package)
   (setq package-archives '(("melpa" . "https://melpa.org/packages/")
   			 ("org" . "https://orgmode.org/elpa/")
                            ("gnu" . "http://elpa.gnu.org/packages/")))
#+end_src

** use-package

#+begin_src emacs-lisp
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** quelpa

#+begin_src emacs-lisp
 (use-package quelpa-use-package)
#+end_src

* Behaviour

** custom variables

Write custom variables into seperate file (so we don't touch init.el).

#+begin_src emacs-lisp
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

** Confirm kill

#+begin_src emacs-lisp
  (setq confirm-kill-emacs 'y-or-n-p)
#+end_src

** Lock files

Lock files are symlinks starting with ~.#~, preventing data loss if multiple
users save the same file.

#+begin_src emacs-lisp
  (setq create-lockfiles nil)
#+end_src

** Autosave

Auto-save to the currently visited file.

#+begin_src emacs-lisp
  (auto-save-visited-mode 1)
#+end_src

Write auto-save-files _also_ to ~/tmp~.

#+begin_src emacs-lisp
  (setq auto-save-file-name-transforms
	`((".*" ,temporary-file-directory t)))
#+end_src

** Backup

Write backups to ~/tmp~.

#+begin_src emacs-lisp
  (setq backup-directory-alist
	`((".*" . ,temporary-file-directory)))
#+end_src

* Completion

** vertico

#+begin_src emacs-lisp
  (use-package vertico
    ;; :custom
    ;; (vertico-scroll-margin 0) ;; Different scroll margin
    ;; (vertico-count 20) ;; Show more candidates
    ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode)
    :bind (:map vertico-map
                ("M-j" . vertico-next)
                ("M-k" . vertico-previous)))

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))

  ;; Emacs minibuffer configurations.
  (use-package emacs
    :custom
    ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
    ;; to switch display modes.
    (context-menu-mode t)
    ;; Support opening new minibuffers from inside existing minibuffers.
    (enable-recursive-minibuffers t)
    ;; Hide commands in M-x which do not work in the current mode.  Vertico
    ;; commands are hidden in normal buffers. This setting is useful beyond
    ;; Vertico.
    (read-extended-command-predicate #'command-completion-default-include-p)
    ;; Do not allow the cursor in the minibuffer prompt
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src

** orderless

This is from the vertico readme

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    ;; Configure a custom style dispatcher (see the Consult wiki)
    ;; (orderless-style-dispatchers '(+orderless-consult-dispatch orderless-affix-dispatch))
    ;; (orderless-component-separator #'orderless-escapable-split-on-space)
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion orderless))))
    (completion-category-defaults nil) ;; Disable defaults, use our settings
    (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring
#+end_src

** marginalia

Annotations in the minibuffer completions.

#+begin_src emacs-lisp
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src

** consult

#+begin_src emacs-lisp
  (use-package consult)
#+end_src

** company

#+begin_src emacs-lisp
  (use-package company
    :hook ((prog-mode LaTeX-mode latex-mode) . company-mode)
    :custom
    (company-minimum-prefix-length 1)
    (company-tooltip-align-annotations t)
    (company-require-match 'never)
    ;; Don't use company in the following modes
    (company-global-modes '(not shell-mode eaf-mode text-mode))
    ;; Trigger completion after a bit
    (company-idle-delay 0.1)
    ;; Number the candidates (use M-1, M-2 etc to select completions).
    (company-show-numbers t)
    :config
    ;; (unless clangd-p (delete 'company-clang company-backends))
    (global-company-mode 1))
#+end_src

** gptel

See capabilities https://github.com/karthink/gptel.

Precondition: an anthropic api-key in =~/anthropic.key=

#+begin_src elisp
  (use-package gptel
    :config
    (defun read-key ()
      (with-temp-buffer
        (insert-file-contents (expand-file-name "~/anthropic.key"))
        (string-trim (buffer-string))))

    (gptel-make-anthropic "Claude" :stream t :key #'read-key)

    (setq gptel-model 'claude-opus-4-5-20251101 ;; get list of models by 'gptel-menu' -> -m
          gptel-backend (gptel-make-anthropic "Claude" :stream t :key #'read-key)))
#+end_src


** TODO yasnippet

#+begin_src emacs-lisp :tangle no
  (use-package yasnippet
    :diminish yas-minor-mode
    :init
    (use-package yasnippet-snippets :after yasnippet)
    :hook
    ((prog-mode LaTeX-mode org-mode markdown-mode) . yas-minor-mode)
    :bind
    (:map yas-minor-mode-map ("C-c C-n" . yas-expand-from-trigger-key))
    (:map yas-keymap
	  (("TAB" . smarter-yas-expand-next-field)
	   ([(tab)] . smarter-yas-expand-next-field)))
    :config
    (yas-reload-all)
    (defun smarter-yas-expand-next-field ()
      ;;  "Try to `yas-expand' then `yas-next-field' at current cursor position."
      (interactive)
      (let ((old-point (point))
	    (old-tick (buffer-chars-modified-tick)))
	(yas-expand)
	(when (and (eq old-point (point))
		   (eq old-tick (buffer-chars-modified-tick)))
	  (ignore-errors (yas-next-field))))))
#+end_src

* Visual changes
** Correct defaults

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (menu-bar-mode -1)
#+end_src

#+begin_src emacs-lisp
  (set-fringe-mode 10)
#+end_src

The scratch buffer being org-mode is more helpful than elisp.

#+begin_src emacs-lisp
  (setq initial-major-mode 'org-mode)
#+end_src

** Visual bell

#+begin_src emacs-lisp
  (setq visible-bell t)
#+end_src

** Line numbers
#+begin_src emacs-lisp
  (column-number-mode)
  (global-display-line-numbers-mode t)
  (dolist (mode '(org-mode-hook
		  vterm-mode-hook
		  term-mode-hook
		  shell-mode-hook
		  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

** Font

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font "Fira Code" :height 120)
#+end_src

** Theme

#+begin_src emacs-lisp
  (use-package doom-themes
    :config
    (setq
     doom-themes-enable-bold t
     doom-themes-enable-italic t)
    (doom-themes-visual-bell-config)
    (load-theme 'doom-gruvbox t)
    (doom-themes-org-config))
#+end_src

*** Cool themes

#+begin_src emacs-lisp :tangle no
  (load-theme 'doom-tomorrow-night t)
  (load-theme 'doom-palenight t)
  (load-theme 'doom-solarized-light t)
#+end_src

** Modeline

Make sure to run ~M-x nerd-icons-install-fonts~ and ~M-x all-the-icons-install-fonts~.

#+begin_src emacs-lisp
  (use-package all-the-icons)

  (use-package doom-modeline
    :config
    (doom-modeline-mode 1))
#+end_src

** Rainbow delimiter

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

** hl-todo

From doom-emacs

#+begin_src emacs-lisp
  (use-package hl-todo
    :hook (prog-mode . hl-todo-mode)
    :config
    (setq hl-todo-highlight-punctuation ":"
          hl-todo-keyword-faces
          `(("TODO"       warning bold)
            ("FIXME"      error bold)
            ("HACK"       font-lock-constant-face bold)
            ("REVIEW"     font-lock-keyword-face bold)
            ("NOTE"       success bold)
            ("DEPRECATED" font-lock-doc-face bold))))
#+end_src


** pretty-mode

- did not get it to work reliably
- resulting symbols are not monospace, stuff doesn't align anymore

#+begin_src emacs-lisp :tangle no
  (use-package pretty-mode
    :config
    (global-pretty-mode 1))
#+end_src

* Ergonomics

** which-key

#+begin_src emacs-lisp
  (use-package which-key
    :diminish
    :init
    (which-key-mode)
    :config
    (setq which-key-idle-delay 0.3))
#+end_src

** helpful

#+begin_src emacs-lisp
  (use-package helpful
    :bind
    ([remap describe-function] . helpful-callable)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key))
#+end_src

* Keybindings

** evil

#+begin_src emacs-lisp
  ;; escape to escape
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src

TODO: rune/evil-hook?

#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    ;; :hook
    ;; (evil-mode . rune/evil-hook)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use viual line motions outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))
#+end_src

#+begin_src emacs-lisp
  (use-package evil-collection
    :after evil
    :custom
    (evil-collection-calendar-want-org-bindings t)
    :config
    (evil-collection-init))
#+end_src

** TODO hydra

short keybindings in limited contexts

** general

#+begin_src emacs-lisp
  (use-package general
    :demand t
    :config
    (general-define-key
     :states '(normal visual insert emacs)
     :keymaps 'override
     :prefix "SPC"
     :non-normal-prefix "C-SPC"
     "w" 'evil-window-map
     "h" 'help-command

     "." 'find-file
     "," 'consult-buffer

     "SPC" 'projectile-command-map

     "s" 'my/open-stuff

     "gg" 'magit
     "gb" 'magit-blame

     "cC" 'eglot
     "ca" 'eglot-code-actions
     "cc" 'compile
     "cf" 'eglot-format-buffer
     "cr" 'eglot-rename
     "cm" 'imenu
     "cd" 'xref-find-definitions
     "cD" 'xref-find-references
     "cs" 'eldoc

     "ni"  'org-insert-structure-template
     "no"  'org-open-at-point
     "nt"  'org-timestamp-inactive
     "nrf" 'org-roam-node-find
     "nri" 'org-roam-node-insert
     "nrt" 'org-roam-tag-add
     "nrdd" 'org-roam-dailies-capture-today
     "nrdt" 'org-roam-dailies-capture-tomorrow
     "nrdy" 'org-roam-dailies-capture-yesterday
     "nrdD" 'org-roam-dailies-goto-today
     "nrdT" 'org-roam-dailies-goto-tomorrow
     "nrdY" 'org-roam-dailies-goto-yesterday
     "nrdc" 'org-roam-dailies-goto-date

     "mp" 'markdown-toggle-markup-hiding

     "pp" 'gptel-send
     "pm" 'gptel-menu))
#+end_src

*** Examples

- https://github.com/tshu-w/.emacs.d/blob/master/lisp/core-keybinds.el
- https://github.com/skyler544/rex/blob/main/config/rex-keybinds.el

* Projects

** projectile

#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :init
    (setq projectile-switch-project-action #'projectile-vc)
    :config
    (projectile-mode)
    :custom
    (projectile-completion-system 'default)
    ;; 'alien leads to frozen "projectile is indexing"
    (projectile-indexing-method 'hybrid)

    ;; This prevents top-down search, so directories with eg. a Makefile do not get recognized as projects.
    ;; What still gets found are parents with .git or .projectile files.
    ;; The reason for this is that the top-down search over tramp takes a long time.
    (projectile-project-root-files-functions
     '(projectile-root-local projectile-root-marked projectile-root-bottom-up)))
#+end_src

Allows using consult to select project if no project is selected.

#+begin_src emacs-lisp
  (use-package consult-projectile
    :after (consult projectile))
#+end_src

Required for ~projectile-ripgrep~ to work.

#+begin_src emacs-lisp
  (use-package rg)
#+end_src

** workspace

Starting a workspace (see [[file:shell.nix]]) in a ghostty window.
Start via ~setsid~ to not have the ghostty window as a child process of emacs.

#+begin_src emacs-lisp
  (defun my/workspace-start ()
    "Launch a Ghostty window as a detached process and run workspace-start in the current directory."
    (interactive)
    (call-process "setsid" nil 0 nil "--fork"
  		 "ghostty" "-e" "fish" "-C" "workspace-start"))
#+end_src

* Version control

** magit

#+begin_src emacs-lisp
  (use-package magit
    :commands
    (magit-status magit-get-current-branch)
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

** git-sync

When a repo has a script ~git-sync.sh~ (https://github.com/simonthum/git-sync) in it's root, call it on save. Call it explicitly with bash because the
shebang does not seem to work if it's invoked via emacs on termux.

#+begin_src emacs-lisp
  (require 'vc-git)

  (defun my/git-sync-buffer (&optional buffer)
    "Run `bash git-sync.sh -ns` at the repo root if BUFFER visits a git-tracked file."
    (interactive)
    (when-let* ((file (buffer-file-name (or buffer (current-buffer))))
  	      (root (vc-git-root file))
  	      (script (expand-file-name "git-sync.sh" root))
  	      ((file-exists-p script))
  	      ((not (string-prefix-p (expand-file-name ".git/" root)
  				     (expand-file-name file))))
  	      ((not (process-live-p (get-process "git-sync")))))

      (let ((default-directory root))
        (make-process
         :name "git-sync"
         :buffer "*git-sync*"
         :command (list "bash" (file-local-name script) "-ns")
         :file-handler t
         :sentinel (lambda (proc _event)
  		   (unless (or (process-live-p proc)
  			       (zerop (process-exit-status proc)))
  		     (message "git-sync failed (%d)"
  			      (process-exit-status proc))))))))

  (add-hook 'after-save-hook #'my/git-sync-buffer)
#+end_src

* Programming

** treesit-auto

Note that the treesitter-grammars are installed by nix in ~../emacs.nix~

#+begin_src emacs-lisp
  (use-package treesit-auto
    :custom (treesit-auto-install nil)
    :config
    (global-treesit-auto-mode)
    (treesit-auto-add-to-auto-mode-alist 'all))
#+end_src

** direnv

#+begin_src emacs-lisp
  (use-package envrc
    :hook
    (after-init . envrc-global-mode))
#+end_src

** editorconfig

#+begin_src emacs-lisp
  (use-package editorconfig
    :config
    (editorconfig-mode 1))
#+end_src

** eglot

This defines ~my/eglot-workspace-configs~ for later language-specific blocks to add to.

#+begin_src emacs-lisp
  (defvar my/eglot-workspace-configs '()
    "Alist of (MODE . CONFIG-PLIST) for per-mode eglot workspace configuration.")

  (use-package eglot
    :defer t
    :config
    (add-to-list 'eglot-server-programs `(csharp-mode . ("OmniSharp" "-lsp")))
    (add-to-list 'eglot-server-programs `(nix-mode . ("nil")))
    (setq-default eglot-workspace-configuration
                  (lambda (_server)
                    (cl-loop for (mode . config) in my/eglot-workspace-configs
                             when (derived-mode-p mode)
                             return config)))
    :hook
    ((python-ts-mode
      haskell-mode
      nix-mode
      rust-ts-mode
      typescript-ts-mode
      tsx-ts-mode
      yaml-ts-mode
      dockerfile-ts-mode) . eglot-ensure))
#+end_src

** flycheck

#+begin_src emacs-lisp
  (use-package flycheck
    :init (global-flycheck-mode)
    :custom
    ;; this fixes 'Error from syntax checker org-lint ...'
    ;; per https://stackoverflow.com/a/79897658
    (flycheck-disabled-checkers '(org-lint))
    )
#+end_src

#+begin_src emacs-lisp
  (use-package flycheck-eglot
    :after (flycheck eglot)
    :config
    (global-flycheck-eglot-mode 1))
#+end_src

** [old] web

#+begin_src emacs-lisp :tangle no
  (use-package multi-web-mode
    :config
    (setq mweb-default-major-mode 'html-mode)
    (setq mweb-tags
	  '((php-mode "<\\?php\\|<\\? \\|<\\?=" "\\?>")
	    (js-mode  "<script[^>]*>" "</script>")
	    (css-mode "<style[^>]*>" "</style>")))
    (setq mweb-filename-extensions '("php" "htm" "html" "ctp" "phtml" "php4" "php5"))
    (multi-web-global-mode 1))
#+end_src

** [old] typesript

ATM just using ~tsx-ts-mode~ and ~nixpkgs.typescript-language-server~ where required.

TODO: github.com/AdamNiederer/ng2-mode

#+begin_src emacs-lisp :tangle no
  (use-package typescript-mode)

  (use-package tide
  :after (company flycheck direnv editorconfig)
  :hook
  ((typescript-ts-mode . tide-setup)
   (tsx-ts-mode . tide-setup)
   ;; tide seems to only honor tsfmt.json. See also github.com/ananthakumaran/tide/issues/96
   (before-save . tide-format-before-save)
   (typescript-ts-mode . tide-hl-identifier-mode)))
#+end_src

** C#

*** lsp: omnisharp

Make sure that omnisharp is installed, e.g. default.nix:

#+begin_src nix :tangle no
{ pkgs ? import <nixpkgs> {}}:

pkgs.mkShell {
  packages = with pkgs; [
    dotnetCorePackages.sdk_8_0
    omnisharp-roslyn
  ];
}
#+end_src

and that eglot knows about it, e.g.

#+begin_src emacs-lisp :tangle no
   (add-to-list 'eglot-server-programs `(csharp-mode . ("OmniSharp" "-lsp")))
#+end_src

omnisharp configuration: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options

** python

#+begin_src emacs-lisp
  (use-package python
    :config
    (setq python-ident-guess-offset-verbos nil))
#+end_src

This guy keeps formatting my file while I'm editing

#+begin_src emacs-lisp :tangle no
  (use-package blacken
    :defer t
    :hook
    (python-ts-mode . blacken-mode))
#+end_src

** rust

#+begin_src emacs-lisp
  (use-package rust-mode)

  (add-to-list 'my/eglot-workspace-configs
               '(rust-ts-mode . (:rust-analyzer (:check (:command "clippy")))))
#+end_src

** nix

#+begin_src emacs-lisp
  (use-package nix-mode
    :mode
    ("\\.nix\\'"))
#+end_src

** haskell

#+begin_src emacs-lisp
  (use-package haskell-mode
    :mode
    ("\\.hs\\'")
    :bind
    (:map haskell-mode-map ("C-c C-c" . haskell-interactive-switch)))
#+end_src

Need [[markdown]] to properly display types in the echo area.

** markdown

Used for editing markdown files, also formatting (e.g. types) in the echo-area.

#+begin_src emacs-lisp
  (use-package markdown-mode
    :mode ("README\\.md\\'" . gfm-mode)
    :custom
    (markdown-fontify-code-blocks-natively t)
    (markdown-command "pandoc")
    :bind (:map markdown-mode-map
                ;; align with org-mode
                ("M-<left>"  . markdown-promote)
                ("M-<right>" . markdown-demote)
                ("M-<up>"    . markdown-move-up)
                ("M-<down>"  . markdown-move-down)
                ("C-c C-c"   . markdown-do))
    :hook ((markdown-mode . visual-line-mode)))
#+end_src

** yaml

[[treesit-auto]] activates ~yaml-ts-mode~ is yaml files.
Relies on the treesitter grammar installed by ~../emacs.nix~,
and the ~yaml-language-server~ from ~configuration.nix~.

#+begin_src emacs-lisp
  ;; whenever you'd use yaml-mode, use yaml-ts-mode instead
  (add-to-list 'major-mode-remap-alist '(yaml-mode . yaml-ts-mode))
#+end_src

Tell eglot to get specific schemas. They are downloaded and cached.

Note that there exists a schema for azure pipelines, but they have
features (expression syntax ~${{ foo }}~) which are not valid yaml.
There is a specific ~azure-pipelines-language-server~ which could be
installed when necessary.

#+begin_src emacs-lisp
  (add-to-list 'my/eglot-workspace-configs
               '(yaml-ts-mode . (:yaml
                                  (:schemas
                                   (;; Compose spec — covers compose.yml, docker-compose.yml,
                                    ;; and variants like docker-compose.override.yml
                                    https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
                                    ["compose.yaml"
                                     "compose.yml"
                                     "compose.*.yaml"
                                     "compose.*.yml"
                                     "docker-compose.yaml"
                                     "docker-compose.yml"
                                     "docker-compose.*.yaml"
                                     "docker-compose.*.yml"]

                                    ;; GitHub Actions workflows
                                    https://json.schemastore.org/github-workflow.json
                                    [".github/workflows/*.yaml"
                                     ".github/workflows/*.yml"]

                                    ;; GitHub Actions composite/reusable action definitions
                                    https://json.schemastore.org/github-action.json
                                    ["action.yaml"
                                     "action.yml"])
                                   ;; Optional but recommended: validation strictness, formatting
                                   :validate t
                                   :format (:enable t)
                                   :completion t
                                   :hover t))))
#+end_src

** docker

*** Dockerfile lsp

[[treesit-auto]] activates ~dockerfile-ts-mode~ in dockerfiles.
eglot auto-activates in ~dockerfile-ts-mode~, the grammar is installed by in ~../emacs.nix~,
and the ~dockerfile-language-server~ is installed by ~configuration.nix~.

*** docker management

Magit-like interface for managing docker, maybe try later
#+begin_src emacs-lisp :tangle no
(use-package docker
  :ensure t
  :bind ("C-c d" . docker))
#+end_src

* org

#+begin_src emacs-lisp
  (use-package org
    :ensure nil
    :defer t
    :custom
    ;; Ask only when evaluating shell blocks
    (org-confirm-babel-evaluate
     (lambda (lang _body)
       (member lang '("shell" "sh" "bash" "zsh" "fish"))))
    (org-babel-sh-command "bash")
    
    (org-todo-keywords
     '((sequence "TODO" "IN-PROGRESS" "REVIEW" "|" "DONE" "CANCELED")))

    (org-babel-csharp-default-target-framework "net10.0")
    :config
    (org-babel-do-load-languages
     'org-babel-load-languages
     '(
       (C . t)
       (csharp . t)
       (dot . t)
       (python . t)
       (plantuml . t)
       (haskell . t)
       (shell . t)
       (mermaid . t)))
    :hook
    ((org-mode . visual-line-mode)))
#+end_src

** babel, csharp

~org-babel-csharp-default-target-framework~ has to be set at the time org loads, so it cannot be default-detected based on direnv.

babel invokes source-block in a way that needs dotnet root to be set. This can be done by adding something along the lines of

#+begin_src nix
  DOTNET_ROOT = "${pkgs.dotnetCorePackages.sdk_10_0}/share/dotnet";
#+end_src

to the flake.

Code-Highlighting in for source blocks in latex export
#+begin_src emacs-lisp
(require 'ox-latex)
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)

(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))

#+end_src

modify org-goto to work nicely with completion frameworks

#+begin_src emacs-lisp
(setq org-goto-interface 'outline-path-completion)
(setq org-outline-path-complete-in-steps nil)
#+end_src

** org-roam

Share the daily-directory with roam on my phone.

#+begin_src emacs-lisp
  (use-package org-roam
    :custom
    (org-roam-directory (file-truename "~/org/roam"))
    (org-roam-dailies-directory (file-truename "~/Dropbox/DropsyncFiles/roam/daily/"))
    (org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
    :config

    (defvar my/org-roam-daily-head
      (concat "#+title: %<%Y-%m-%d>\n"
              "* [0/0] Tasks\n"
              "* Journal\n"
              "* Refile\n"))

    (setq org-roam-dailies-capture-templates
  	`(("d" "default" entry "* %?"
             :target (file+head+olp "%<%Y-%m-%d>.org" ,my/org-roam-daily-head ("Refile")))
            ("j" "journal" entry "* %?"
             :target (file+head+olp "%<%Y-%m-%d>.org" ,my/org-roam-daily-head ("Journal")))
            ("t" "task" entry "* TODO %?"
             :target (file+head+olp "%<%Y-%m-%d>.org" ,my/org-roam-daily-head ("Tasks")))))

    (org-roam-db-autosync-mode))
#+end_src

** mermaid

Requires ~mmdc~ (mermaid-cli) in path, and ~mermaid~ to be registered with ~org-babel-languages~.

#+begin_src emacs-lisp
  (use-package ob-mermaid)
#+end_src

Diagram example:

#+begin_src mermaid :file test.png :tangle no
sequenceDiagram
 A-->B: Works!
#+end_src

* Various

** http server

#+begin_src emacs-lisp
  (use-package simple-httpd)
#+end_src

** stuff

#+begin_src emacs-lisp
  (defun my/open-stuff ()
    "Open stuff.org in a new buffer."
    (interactive)
  (find-file "~/Dropbox/DropsyncFiles/stuff.org"))
#+end_src
